// Copyright © 2022 AMIS Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.20.3
// source: crypto/tss/eddsa/frost/signer/message.proto

package signer

import (
	ecpointgrouplaw "github.com/getamis/alice/crypto/ecpointgrouplaw"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type values must increase with protocol order (MsgMain rejects older types).
type Type int32

const (
	Type_Round1Digest Type = 0
	Type_Round1       Type = 1
	Type_Round2Digest Type = 2
	Type_Round2       Type = 3
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "Round1Digest",
		1: "Round1",
		2: "Round2Digest",
		3: "Round2",
	}
	Type_value = map[string]int32{
		"Round1Digest": 0,
		"Round1":       1,
		"Round2Digest": 2,
		"Round2":       3,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_crypto_tss_eddsa_frost_signer_message_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_crypto_tss_eddsa_frost_signer_message_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_crypto_tss_eddsa_frost_signer_message_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  Type                   `protobuf:"varint,1,opt,name=type,proto3,enum=getamis.alice.crypto.tss.eddsa.frost.signer.Type" json:"type,omitempty"`
	Id    string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*Message_Round1Digest
	//	*Message_Round1
	//	*Message_Round2Digest
	//	*Message_Round2
	Body          isMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_crypto_tss_eddsa_frost_signer_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_tss_eddsa_frost_signer_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_crypto_tss_eddsa_frost_signer_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_Round1Digest
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetBody() isMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Message) GetRound1Digest() *Round1DigestMsg {
	if x != nil {
		if x, ok := x.Body.(*Message_Round1Digest); ok {
			return x.Round1Digest
		}
	}
	return nil
}

func (x *Message) GetRound1() *BodyRound1 {
	if x != nil {
		if x, ok := x.Body.(*Message_Round1); ok {
			return x.Round1
		}
	}
	return nil
}

func (x *Message) GetRound2Digest() *Round2DigestMsg {
	if x != nil {
		if x, ok := x.Body.(*Message_Round2Digest); ok {
			return x.Round2Digest
		}
	}
	return nil
}

func (x *Message) GetRound2() *BodyRound2 {
	if x != nil {
		if x, ok := x.Body.(*Message_Round2); ok {
			return x.Round2
		}
	}
	return nil
}

type isMessage_Body interface {
	isMessage_Body()
}

type Message_Round1Digest struct {
	Round1Digest *Round1DigestMsg `protobuf:"bytes,10,opt,name=round1Digest,proto3,oneof"`
}

type Message_Round1 struct {
	Round1 *BodyRound1 `protobuf:"bytes,4,opt,name=round1,proto3,oneof"`
}

type Message_Round2Digest struct {
	Round2Digest *Round2DigestMsg `protobuf:"bytes,11,opt,name=round2Digest,proto3,oneof"`
}

type Message_Round2 struct {
	Round2 *BodyRound2 `protobuf:"bytes,5,opt,name=round2,proto3,oneof"`
}

func (*Message_Round1Digest) isMessage_Body() {}

func (*Message_Round1) isMessage_Body() {}

func (*Message_Round2Digest) isMessage_Body() {}

func (*Message_Round2) isMessage_Body() {}

type PeerDigestEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Digest        []byte                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"` // exactly 32 bytes (blake2b-256)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerDigestEntry) Reset() {
	*x = PeerDigestEntry{}
	mi := &file_crypto_tss_eddsa_frost_signer_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerDigestEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerDigestEntry) ProtoMessage() {}

func (x *PeerDigestEntry) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_tss_eddsa_frost_signer_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerDigestEntry.ProtoReflect.Descriptor instead.
func (*PeerDigestEntry) Descriptor() ([]byte, []int) {
	return file_crypto_tss_eddsa_frost_signer_message_proto_rawDescGZIP(), []int{1}
}

func (x *PeerDigestEntry) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *PeerDigestEntry) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

type Round1DigestMsg struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	D             *ecpointgrouplaw.EcPointMessage `protobuf:"bytes,1,opt,name=D,proto3" json:"D,omitempty"`
	E             *ecpointgrouplaw.EcPointMessage `protobuf:"bytes,2,opt,name=E,proto3" json:"E,omitempty"`
	ToPeer        []*PeerDigestEntry              `protobuf:"bytes,3,rep,name=to_peer,json=toPeer,proto3" json:"to_peer,omitempty"`
	TableRoot     []byte                          `protobuf:"bytes,4,opt,name=table_root,json=tableRoot,proto3" json:"table_root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Round1DigestMsg) Reset() {
	*x = Round1DigestMsg{}
	mi := &file_crypto_tss_eddsa_frost_signer_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Round1DigestMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round1DigestMsg) ProtoMessage() {}

func (x *Round1DigestMsg) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_tss_eddsa_frost_signer_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round1DigestMsg.ProtoReflect.Descriptor instead.
func (*Round1DigestMsg) Descriptor() ([]byte, []int) {
	return file_crypto_tss_eddsa_frost_signer_message_proto_rawDescGZIP(), []int{2}
}

func (x *Round1DigestMsg) GetD() *ecpointgrouplaw.EcPointMessage {
	if x != nil {
		return x.D
	}
	return nil
}

func (x *Round1DigestMsg) GetE() *ecpointgrouplaw.EcPointMessage {
	if x != nil {
		return x.E
	}
	return nil
}

func (x *Round1DigestMsg) GetToPeer() []*PeerDigestEntry {
	if x != nil {
		return x.ToPeer
	}
	return nil
}

func (x *Round1DigestMsg) GetTableRoot() []byte {
	if x != nil {
		return x.TableRoot
	}
	return nil
}

type Round2DigestMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToPeer        []*PeerDigestEntry     `protobuf:"bytes,1,rep,name=to_peer,json=toPeer,proto3" json:"to_peer,omitempty"`
	TableRoot     []byte                 `protobuf:"bytes,2,opt,name=table_root,json=tableRoot,proto3" json:"table_root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Round2DigestMsg) Reset() {
	*x = Round2DigestMsg{}
	mi := &file_crypto_tss_eddsa_frost_signer_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Round2DigestMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round2DigestMsg) ProtoMessage() {}

func (x *Round2DigestMsg) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_tss_eddsa_frost_signer_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round2DigestMsg.ProtoReflect.Descriptor instead.
func (*Round2DigestMsg) Descriptor() ([]byte, []int) {
	return file_crypto_tss_eddsa_frost_signer_message_proto_rawDescGZIP(), []int{3}
}

func (x *Round2DigestMsg) GetToPeer() []*PeerDigestEntry {
	if x != nil {
		return x.ToPeer
	}
	return nil
}

func (x *Round2DigestMsg) GetTableRoot() []byte {
	if x != nil {
		return x.TableRoot
	}
	return nil
}

type BodyRound1 struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	D             *ecpointgrouplaw.EcPointMessage `protobuf:"bytes,1,opt,name=D,proto3" json:"D,omitempty"`
	E             *ecpointgrouplaw.EcPointMessage `protobuf:"bytes,2,opt,name=E,proto3" json:"E,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BodyRound1) Reset() {
	*x = BodyRound1{}
	mi := &file_crypto_tss_eddsa_frost_signer_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BodyRound1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodyRound1) ProtoMessage() {}

func (x *BodyRound1) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_tss_eddsa_frost_signer_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodyRound1.ProtoReflect.Descriptor instead.
func (*BodyRound1) Descriptor() ([]byte, []int) {
	return file_crypto_tss_eddsa_frost_signer_message_proto_rawDescGZIP(), []int{4}
}

func (x *BodyRound1) GetD() *ecpointgrouplaw.EcPointMessage {
	if x != nil {
		return x.D
	}
	return nil
}

func (x *BodyRound1) GetE() *ecpointgrouplaw.EcPointMessage {
	if x != nil {
		return x.E
	}
	return nil
}

type BodyRound2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zi            []byte                 `protobuf:"bytes,1,opt,name=zi,proto3" json:"zi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BodyRound2) Reset() {
	*x = BodyRound2{}
	mi := &file_crypto_tss_eddsa_frost_signer_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BodyRound2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodyRound2) ProtoMessage() {}

func (x *BodyRound2) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_tss_eddsa_frost_signer_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodyRound2.ProtoReflect.Descriptor instead.
func (*BodyRound2) Descriptor() ([]byte, []int) {
	return file_crypto_tss_eddsa_frost_signer_message_proto_rawDescGZIP(), []int{5}
}

func (x *BodyRound2) GetZi() []byte {
	if x != nil {
		return x.Zi
	}
	return nil
}

type BMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             []byte                 `protobuf:"bytes,1,opt,name=x,proto3" json:"x,omitempty"`
	D             []byte                 `protobuf:"bytes,2,opt,name=D,proto3" json:"D,omitempty"`
	E             []byte                 `protobuf:"bytes,3,opt,name=E,proto3" json:"E,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BMessage) Reset() {
	*x = BMessage{}
	mi := &file_crypto_tss_eddsa_frost_signer_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BMessage) ProtoMessage() {}

func (x *BMessage) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_tss_eddsa_frost_signer_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BMessage.ProtoReflect.Descriptor instead.
func (*BMessage) Descriptor() ([]byte, []int) {
	return file_crypto_tss_eddsa_frost_signer_message_proto_rawDescGZIP(), []int{6}
}

func (x *BMessage) GetX() []byte {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *BMessage) GetD() []byte {
	if x != nil {
		return x.D
	}
	return nil
}

func (x *BMessage) GetE() []byte {
	if x != nil {
		return x.E
	}
	return nil
}

var File_crypto_tss_eddsa_frost_signer_message_proto protoreflect.FileDescriptor

const file_crypto_tss_eddsa_frost_signer_message_proto_rawDesc = "" +
	"\n" +
	"+crypto/tss/eddsa/frost/signer/message.proto\x12+getamis.alice.crypto.tss.eddsa.frost.signer\x1a;github.com/getamis/alice/crypto/ecpointgrouplaw/point.proto\"\xd6\x03\n" +
	"\aMessage\x12E\n" +
	"\x04type\x18\x01 \x01(\x0e21.getamis.alice.crypto.tss.eddsa.frost.signer.TypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12b\n" +
	"\fround1Digest\x18\n" +
	" \x01(\v2<.getamis.alice.crypto.tss.eddsa.frost.signer.Round1DigestMsgH\x00R\fround1Digest\x12Q\n" +
	"\x06round1\x18\x04 \x01(\v27.getamis.alice.crypto.tss.eddsa.frost.signer.BodyRound1H\x00R\x06round1\x12b\n" +
	"\fround2Digest\x18\v \x01(\v2<.getamis.alice.crypto.tss.eddsa.frost.signer.Round2DigestMsgH\x00R\fround2Digest\x12Q\n" +
	"\x06round2\x18\x05 \x01(\v27.getamis.alice.crypto.tss.eddsa.frost.signer.BodyRound2H\x00R\x06round2B\x06\n" +
	"\x04body\"B\n" +
	"\x0fPeerDigestEntry\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\fR\x06digest\"\x8f\x02\n" +
	"\x0fRound1DigestMsg\x12B\n" +
	"\x01D\x18\x01 \x01(\v24.getamis.alice.crypto.ecpointgrouplaw.EcPointMessageR\x01D\x12B\n" +
	"\x01E\x18\x02 \x01(\v24.getamis.alice.crypto.ecpointgrouplaw.EcPointMessageR\x01E\x12U\n" +
	"\ato_peer\x18\x03 \x03(\v2<.getamis.alice.crypto.tss.eddsa.frost.signer.PeerDigestEntryR\x06toPeer\x12\x1d\n" +
	"\n" +
	"table_root\x18\x04 \x01(\fR\ttableRoot\"\x87\x01\n" +
	"\x0fRound2DigestMsg\x12U\n" +
	"\ato_peer\x18\x01 \x03(\v2<.getamis.alice.crypto.tss.eddsa.frost.signer.PeerDigestEntryR\x06toPeer\x12\x1d\n" +
	"\n" +
	"table_root\x18\x02 \x01(\fR\ttableRoot\"\x94\x01\n" +
	"\n" +
	"BodyRound1\x12B\n" +
	"\x01D\x18\x01 \x01(\v24.getamis.alice.crypto.ecpointgrouplaw.EcPointMessageR\x01D\x12B\n" +
	"\x01E\x18\x02 \x01(\v24.getamis.alice.crypto.ecpointgrouplaw.EcPointMessageR\x01E\"\x1c\n" +
	"\n" +
	"BodyRound2\x12\x0e\n" +
	"\x02zi\x18\x01 \x01(\fR\x02zi\"4\n" +
	"\bBMessage\x12\f\n" +
	"\x01x\x18\x01 \x01(\fR\x01x\x12\f\n" +
	"\x01D\x18\x02 \x01(\fR\x01D\x12\f\n" +
	"\x01E\x18\x03 \x01(\fR\x01E*B\n" +
	"\x04Type\x12\x10\n" +
	"\fRound1Digest\x10\x00\x12\n" +
	"\n" +
	"\x06Round1\x10\x01\x12\x10\n" +
	"\fRound2Digest\x10\x02\x12\n" +
	"\n" +
	"\x06Round2\x10\x03B8Z6github.com/getamis/alice/crypto/tss/eddsa/frost/signerb\x06proto3"

var (
	file_crypto_tss_eddsa_frost_signer_message_proto_rawDescOnce sync.Once
	file_crypto_tss_eddsa_frost_signer_message_proto_rawDescData []byte
)

func file_crypto_tss_eddsa_frost_signer_message_proto_rawDescGZIP() []byte {
	file_crypto_tss_eddsa_frost_signer_message_proto_rawDescOnce.Do(func() {
		file_crypto_tss_eddsa_frost_signer_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crypto_tss_eddsa_frost_signer_message_proto_rawDesc), len(file_crypto_tss_eddsa_frost_signer_message_proto_rawDesc)))
	})
	return file_crypto_tss_eddsa_frost_signer_message_proto_rawDescData
}

var file_crypto_tss_eddsa_frost_signer_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_crypto_tss_eddsa_frost_signer_message_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_crypto_tss_eddsa_frost_signer_message_proto_goTypes = []any{
	(Type)(0),                              // 0: getamis.alice.crypto.tss.eddsa.frost.signer.Type
	(*Message)(nil),                        // 1: getamis.alice.crypto.tss.eddsa.frost.signer.Message
	(*PeerDigestEntry)(nil),                // 2: getamis.alice.crypto.tss.eddsa.frost.signer.PeerDigestEntry
	(*Round1DigestMsg)(nil),                // 3: getamis.alice.crypto.tss.eddsa.frost.signer.Round1DigestMsg
	(*Round2DigestMsg)(nil),                // 4: getamis.alice.crypto.tss.eddsa.frost.signer.Round2DigestMsg
	(*BodyRound1)(nil),                     // 5: getamis.alice.crypto.tss.eddsa.frost.signer.BodyRound1
	(*BodyRound2)(nil),                     // 6: getamis.alice.crypto.tss.eddsa.frost.signer.BodyRound2
	(*BMessage)(nil),                       // 7: getamis.alice.crypto.tss.eddsa.frost.signer.BMessage
	(*ecpointgrouplaw.EcPointMessage)(nil), // 8: getamis.alice.crypto.ecpointgrouplaw.EcPointMessage
}
var file_crypto_tss_eddsa_frost_signer_message_proto_depIdxs = []int32{
	0,  // 0: getamis.alice.crypto.tss.eddsa.frost.signer.Message.type:type_name -> getamis.alice.crypto.tss.eddsa.frost.signer.Type
	3,  // 1: getamis.alice.crypto.tss.eddsa.frost.signer.Message.round1Digest:type_name -> getamis.alice.crypto.tss.eddsa.frost.signer.Round1DigestMsg
	5,  // 2: getamis.alice.crypto.tss.eddsa.frost.signer.Message.round1:type_name -> getamis.alice.crypto.tss.eddsa.frost.signer.BodyRound1
	4,  // 3: getamis.alice.crypto.tss.eddsa.frost.signer.Message.round2Digest:type_name -> getamis.alice.crypto.tss.eddsa.frost.signer.Round2DigestMsg
	6,  // 4: getamis.alice.crypto.tss.eddsa.frost.signer.Message.round2:type_name -> getamis.alice.crypto.tss.eddsa.frost.signer.BodyRound2
	8,  // 5: getamis.alice.crypto.tss.eddsa.frost.signer.Round1DigestMsg.D:type_name -> getamis.alice.crypto.ecpointgrouplaw.EcPointMessage
	8,  // 6: getamis.alice.crypto.tss.eddsa.frost.signer.Round1DigestMsg.E:type_name -> getamis.alice.crypto.ecpointgrouplaw.EcPointMessage
	2,  // 7: getamis.alice.crypto.tss.eddsa.frost.signer.Round1DigestMsg.to_peer:type_name -> getamis.alice.crypto.tss.eddsa.frost.signer.PeerDigestEntry
	2,  // 8: getamis.alice.crypto.tss.eddsa.frost.signer.Round2DigestMsg.to_peer:type_name -> getamis.alice.crypto.tss.eddsa.frost.signer.PeerDigestEntry
	8,  // 9: getamis.alice.crypto.tss.eddsa.frost.signer.BodyRound1.D:type_name -> getamis.alice.crypto.ecpointgrouplaw.EcPointMessage
	8,  // 10: getamis.alice.crypto.tss.eddsa.frost.signer.BodyRound1.E:type_name -> getamis.alice.crypto.ecpointgrouplaw.EcPointMessage
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_crypto_tss_eddsa_frost_signer_message_proto_init() }
func file_crypto_tss_eddsa_frost_signer_message_proto_init() {
	if File_crypto_tss_eddsa_frost_signer_message_proto != nil {
		return
	}
	file_crypto_tss_eddsa_frost_signer_message_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_Round1Digest)(nil),
		(*Message_Round1)(nil),
		(*Message_Round2Digest)(nil),
		(*Message_Round2)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crypto_tss_eddsa_frost_signer_message_proto_rawDesc), len(file_crypto_tss_eddsa_frost_signer_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_crypto_tss_eddsa_frost_signer_message_proto_goTypes,
		DependencyIndexes: file_crypto_tss_eddsa_frost_signer_message_proto_depIdxs,
		EnumInfos:         file_crypto_tss_eddsa_frost_signer_message_proto_enumTypes,
		MessageInfos:      file_crypto_tss_eddsa_frost_signer_message_proto_msgTypes,
	}.Build()
	File_crypto_tss_eddsa_frost_signer_message_proto = out.File
	file_crypto_tss_eddsa_frost_signer_message_proto_goTypes = nil
	file_crypto_tss_eddsa_frost_signer_message_proto_depIdxs = nil
}
