// Copyright © 2022 AMIS Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.20.3
// source: github.com/getamis/alice/crypto/tss/ecdsa/cggmp/sign/message.proto

package sign

import (
	ecpointgrouplaw "github.com/getamis/alice/crypto/ecpointgrouplaw"
	paillier "github.com/getamis/alice/crypto/zkproof/paillier"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_Round1 Type = 0
	Type_Round2 Type = 1
	Type_Round3 Type = 2
	Type_Round4 Type = 3
	Type_Err1   Type = 4
	Type_Err2   Type = 5
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "Round1",
		1: "Round2",
		2: "Round3",
		3: "Round4",
		4: "Err1",
		5: "Err2",
	}
	Type_value = map[string]int32{
		"Round1": 0,
		"Round2": 1,
		"Round3": 2,
		"Round4": 3,
		"Err1":   4,
		"Err2":   5,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  Type                   `protobuf:"varint,1,opt,name=type,proto3,enum=getamis.alice.crypto.tss.ecdsa.cggmp.sign.Type" json:"type,omitempty"`
	Id    string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*Message_Round1
	//	*Message_Round2
	//	*Message_Round3
	//	*Message_Round4
	//	*Message_Err1
	//	*Message_Err2
	Body          isMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_Round1
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetBody() isMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Message) GetRound1() *Round1Msg {
	if x != nil {
		if x, ok := x.Body.(*Message_Round1); ok {
			return x.Round1
		}
	}
	return nil
}

func (x *Message) GetRound2() *Round2Msg {
	if x != nil {
		if x, ok := x.Body.(*Message_Round2); ok {
			return x.Round2
		}
	}
	return nil
}

func (x *Message) GetRound3() *Round3Msg {
	if x != nil {
		if x, ok := x.Body.(*Message_Round3); ok {
			return x.Round3
		}
	}
	return nil
}

func (x *Message) GetRound4() *Round4Msg {
	if x != nil {
		if x, ok := x.Body.(*Message_Round4); ok {
			return x.Round4
		}
	}
	return nil
}

func (x *Message) GetErr1() *Err1Msg {
	if x != nil {
		if x, ok := x.Body.(*Message_Err1); ok {
			return x.Err1
		}
	}
	return nil
}

func (x *Message) GetErr2() *Err2Msg {
	if x != nil {
		if x, ok := x.Body.(*Message_Err2); ok {
			return x.Err2
		}
	}
	return nil
}

type isMessage_Body interface {
	isMessage_Body()
}

type Message_Round1 struct {
	Round1 *Round1Msg `protobuf:"bytes,4,opt,name=round1,proto3,oneof"`
}

type Message_Round2 struct {
	Round2 *Round2Msg `protobuf:"bytes,5,opt,name=round2,proto3,oneof"`
}

type Message_Round3 struct {
	Round3 *Round3Msg `protobuf:"bytes,6,opt,name=round3,proto3,oneof"`
}

type Message_Round4 struct {
	Round4 *Round4Msg `protobuf:"bytes,7,opt,name=round4,proto3,oneof"`
}

type Message_Err1 struct {
	// Error message
	Err1 *Err1Msg `protobuf:"bytes,8,opt,name=err1,proto3,oneof"`
}

type Message_Err2 struct {
	Err2 *Err2Msg `protobuf:"bytes,9,opt,name=err2,proto3,oneof"`
}

func (*Message_Round1) isMessage_Body() {}

func (*Message_Round2) isMessage_Body() {}

func (*Message_Round3) isMessage_Body() {}

func (*Message_Round4) isMessage_Body() {}

func (*Message_Err1) isMessage_Body() {}

func (*Message_Err2) isMessage_Body() {}

type Round1Msg struct {
	state           protoimpl.MessageState        `protogen:"open.v1"`
	KCiphertext     []byte                        `protobuf:"bytes,1,opt,name=kCiphertext,proto3" json:"kCiphertext,omitempty"`
	GammaCiphertext []byte                        `protobuf:"bytes,2,opt,name=gammaCiphertext,proto3" json:"gammaCiphertext,omitempty"`
	Psi             *paillier.EncryptRangeMessage `protobuf:"bytes,3,opt,name=psi,proto3" json:"psi,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Round1Msg) Reset() {
	*x = Round1Msg{}
	mi := &file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Round1Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round1Msg) ProtoMessage() {}

func (x *Round1Msg) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round1Msg.ProtoReflect.Descriptor instead.
func (*Round1Msg) Descriptor() ([]byte, []int) {
	return file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_rawDescGZIP(), []int{1}
}

func (x *Round1Msg) GetKCiphertext() []byte {
	if x != nil {
		return x.KCiphertext
	}
	return nil
}

func (x *Round1Msg) GetGammaCiphertext() []byte {
	if x != nil {
		return x.GammaCiphertext
	}
	return nil
}

func (x *Round1Msg) GetPsi() *paillier.EncryptRangeMessage {
	if x != nil {
		return x.Psi
	}
	return nil
}

type Round2Msg struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	D             []byte                                    `protobuf:"bytes,1,opt,name=D,proto3" json:"D,omitempty"`
	F             []byte                                    `protobuf:"bytes,2,opt,name=F,proto3" json:"F,omitempty"`
	Dhat          []byte                                    `protobuf:"bytes,3,opt,name=Dhat,proto3" json:"Dhat,omitempty"`
	Fhat          []byte                                    `protobuf:"bytes,4,opt,name=Fhat,proto3" json:"Fhat,omitempty"`
	Psi           *paillier.PaillierAffAndGroupRangeMessage `protobuf:"bytes,5,opt,name=psi,proto3" json:"psi,omitempty"`
	Psihat        *paillier.PaillierAffAndGroupRangeMessage `protobuf:"bytes,6,opt,name=psihat,proto3" json:"psihat,omitempty"`
	Psipai        *paillier.LogStarMessage                  `protobuf:"bytes,7,opt,name=psipai,proto3" json:"psipai,omitempty"`
	Gamma         *ecpointgrouplaw.EcPointMessage           `protobuf:"bytes,8,opt,name=Gamma,proto3" json:"Gamma,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Round2Msg) Reset() {
	*x = Round2Msg{}
	mi := &file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Round2Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round2Msg) ProtoMessage() {}

func (x *Round2Msg) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round2Msg.ProtoReflect.Descriptor instead.
func (*Round2Msg) Descriptor() ([]byte, []int) {
	return file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_rawDescGZIP(), []int{2}
}

func (x *Round2Msg) GetD() []byte {
	if x != nil {
		return x.D
	}
	return nil
}

func (x *Round2Msg) GetF() []byte {
	if x != nil {
		return x.F
	}
	return nil
}

func (x *Round2Msg) GetDhat() []byte {
	if x != nil {
		return x.Dhat
	}
	return nil
}

func (x *Round2Msg) GetFhat() []byte {
	if x != nil {
		return x.Fhat
	}
	return nil
}

func (x *Round2Msg) GetPsi() *paillier.PaillierAffAndGroupRangeMessage {
	if x != nil {
		return x.Psi
	}
	return nil
}

func (x *Round2Msg) GetPsihat() *paillier.PaillierAffAndGroupRangeMessage {
	if x != nil {
		return x.Psihat
	}
	return nil
}

func (x *Round2Msg) GetPsipai() *paillier.LogStarMessage {
	if x != nil {
		return x.Psipai
	}
	return nil
}

func (x *Round2Msg) GetGamma() *ecpointgrouplaw.EcPointMessage {
	if x != nil {
		return x.Gamma
	}
	return nil
}

type Round3Msg struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Delta         string                          `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"`
	BigDelta      *ecpointgrouplaw.EcPointMessage `protobuf:"bytes,2,opt,name=bigDelta,proto3" json:"bigDelta,omitempty"`
	Psidoublepai  *paillier.LogStarMessage        `protobuf:"bytes,3,opt,name=psidoublepai,proto3" json:"psidoublepai,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Round3Msg) Reset() {
	*x = Round3Msg{}
	mi := &file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Round3Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round3Msg) ProtoMessage() {}

func (x *Round3Msg) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round3Msg.ProtoReflect.Descriptor instead.
func (*Round3Msg) Descriptor() ([]byte, []int) {
	return file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_rawDescGZIP(), []int{3}
}

func (x *Round3Msg) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *Round3Msg) GetBigDelta() *ecpointgrouplaw.EcPointMessage {
	if x != nil {
		return x.BigDelta
	}
	return nil
}

func (x *Round3Msg) GetPsidoublepai() *paillier.LogStarMessage {
	if x != nil {
		return x.Psidoublepai
	}
	return nil
}

type Round4Msg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sigmai        []byte                 `protobuf:"bytes,1,opt,name=sigmai,proto3" json:"sigmai,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Round4Msg) Reset() {
	*x = Round4Msg{}
	mi := &file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Round4Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Round4Msg) ProtoMessage() {}

func (x *Round4Msg) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Round4Msg.ProtoReflect.Descriptor instead.
func (*Round4Msg) Descriptor() ([]byte, []int) {
	return file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_rawDescGZIP(), []int{4}
}

func (x *Round4Msg) GetSigmai() []byte {
	if x != nil {
		return x.Sigmai
	}
	return nil
}

type Err1Msg struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	KgammaCiphertext []byte                  `protobuf:"bytes,1,opt,name=kgammaCiphertext,proto3" json:"kgammaCiphertext,omitempty"`
	MulProof         *paillier.MulMessage    `protobuf:"bytes,2,opt,name=mulProof,proto3" json:"mulProof,omitempty"`
	Peers            map[string]*Err1PeerMsg `protobuf:"bytes,3,rep,name=peers,proto3" json:"peers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Err1Msg) Reset() {
	*x = Err1Msg{}
	mi := &file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Err1Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Err1Msg) ProtoMessage() {}

func (x *Err1Msg) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Err1Msg.ProtoReflect.Descriptor instead.
func (*Err1Msg) Descriptor() ([]byte, []int) {
	return file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_rawDescGZIP(), []int{5}
}

func (x *Err1Msg) GetKgammaCiphertext() []byte {
	if x != nil {
		return x.KgammaCiphertext
	}
	return nil
}

func (x *Err1Msg) GetMulProof() *paillier.MulMessage {
	if x != nil {
		return x.MulProof
	}
	return nil
}

func (x *Err1Msg) GetPeers() map[string]*Err1PeerMsg {
	if x != nil {
		return x.Peers
	}
	return nil
}

type Err1PeerMsg struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	DecModQ *paillier.DecryMessage `protobuf:"bytes,1,opt,name=decModQ,proto3" json:"decModQ,omitempty"`
	// Untranslated MtA product C0; DecModQ uses PublicX(δ)=(δ+Σc·N) mod q.
	ProductCiphertext []byte `protobuf:"bytes,2,opt,name=productCiphertext,proto3" json:"productCiphertext,omitempty"`
	// D_{peer→prover} (under prover Paillier) used in the product.
	D []byte `protobuf:"bytes,3,opt,name=d,proto3" json:"d,omitempty"`
	// F_{prover→peer} (under prover Paillier) used in the product.
	F             []byte `protobuf:"bytes,4,opt,name=f,proto3" json:"f,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Err1PeerMsg) Reset() {
	*x = Err1PeerMsg{}
	mi := &file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Err1PeerMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Err1PeerMsg) ProtoMessage() {}

func (x *Err1PeerMsg) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Err1PeerMsg.ProtoReflect.Descriptor instead.
func (*Err1PeerMsg) Descriptor() ([]byte, []int) {
	return file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_rawDescGZIP(), []int{6}
}

func (x *Err1PeerMsg) GetDecModQ() *paillier.DecryMessage {
	if x != nil {
		return x.DecModQ
	}
	return nil
}

func (x *Err1PeerMsg) GetProductCiphertext() []byte {
	if x != nil {
		return x.ProductCiphertext
	}
	return nil
}

func (x *Err1PeerMsg) GetD() []byte {
	if x != nil {
		return x.D
	}
	return nil
}

func (x *Err1PeerMsg) GetF() []byte {
	if x != nil {
		return x.F
	}
	return nil
}

type Err2Msg struct {
	state                 protoimpl.MessageState  `protogen:"open.v1"`
	KMulBkShareCiphertext []byte                  `protobuf:"bytes,1,opt,name=kMulBkShareCiphertext,proto3" json:"kMulBkShareCiphertext,omitempty"`
	Peers                 map[string]*Err2PeerMsg `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// χ_i for Scheme A' (PublicX(χ) and σ−r·χ).
	Chi           []byte `protobuf:"bytes,3,opt,name=chi,proto3" json:"chi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Err2Msg) Reset() {
	*x = Err2Msg{}
	mi := &file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Err2Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Err2Msg) ProtoMessage() {}

func (x *Err2Msg) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Err2Msg.ProtoReflect.Descriptor instead.
func (*Err2Msg) Descriptor() ([]byte, []int) {
	return file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_rawDescGZIP(), []int{7}
}

func (x *Err2Msg) GetKMulBkShareCiphertext() []byte {
	if x != nil {
		return x.KMulBkShareCiphertext
	}
	return nil
}

func (x *Err2Msg) GetPeers() map[string]*Err2PeerMsg {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *Err2Msg) GetChi() []byte {
	if x != nil {
		return x.Chi
	}
	return nil
}

type Err2PeerMsg struct {
	state        protoimpl.MessageState   `protogen:"open.v1"`
	MulStarProof *paillier.MulStarMessage `protobuf:"bytes,1,opt,name=mulStarProof,proto3" json:"mulStarProof,omitempty"`
	// DecModQ on untranslated C_inner vs PublicX(χ).
	DecModQ           *paillier.DecryMessage `protobuf:"bytes,2,opt,name=decModQ,proto3" json:"decModQ,omitempty"`
	ProductCiphertext []byte                 `protobuf:"bytes,3,opt,name=productCiphertext,proto3" json:"productCiphertext,omitempty"`
	D                 []byte                 `protobuf:"bytes,4,opt,name=d,proto3" json:"d,omitempty"`
	F                 []byte                 `protobuf:"bytes,5,opt,name=f,proto3" json:"f,omitempty"`
	// DecModQ on K^m vs (σ − r·χ) mod q.
	DecModQKm     *paillier.DecryMessage `protobuf:"bytes,6,opt,name=decModQKm,proto3" json:"decModQKm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Err2PeerMsg) Reset() {
	*x = Err2PeerMsg{}
	mi := &file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Err2PeerMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Err2PeerMsg) ProtoMessage() {}

func (x *Err2PeerMsg) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Err2PeerMsg.ProtoReflect.Descriptor instead.
func (*Err2PeerMsg) Descriptor() ([]byte, []int) {
	return file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_rawDescGZIP(), []int{8}
}

func (x *Err2PeerMsg) GetMulStarProof() *paillier.MulStarMessage {
	if x != nil {
		return x.MulStarProof
	}
	return nil
}

func (x *Err2PeerMsg) GetDecModQ() *paillier.DecryMessage {
	if x != nil {
		return x.DecModQ
	}
	return nil
}

func (x *Err2PeerMsg) GetProductCiphertext() []byte {
	if x != nil {
		return x.ProductCiphertext
	}
	return nil
}

func (x *Err2PeerMsg) GetD() []byte {
	if x != nil {
		return x.D
	}
	return nil
}

func (x *Err2PeerMsg) GetF() []byte {
	if x != nil {
		return x.F
	}
	return nil
}

func (x *Err2PeerMsg) GetDecModQKm() *paillier.DecryMessage {
	if x != nil {
		return x.DecModQKm
	}
	return nil
}

var File_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto protoreflect.FileDescriptor

const file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_rawDesc = "" +
	"\n" +
	"Bgithub.com/getamis/alice/crypto/tss/ecdsa/cggmp/sign/message.proto\x12)getamis.alice.crypto.tss.ecdsa.cggmp.sign\x1a;github.com/getamis/alice/crypto/ecpointgrouplaw/point.proto\x1a>github.com/getamis/alice/crypto/zkproof/paillier/message.proto\"\xba\x04\n" +
	"\aMessage\x12C\n" +
	"\x04type\x18\x01 \x01(\x0e2/.getamis.alice.crypto.tss.ecdsa.cggmp.sign.TypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12N\n" +
	"\x06round1\x18\x04 \x01(\v24.getamis.alice.crypto.tss.ecdsa.cggmp.sign.Round1MsgH\x00R\x06round1\x12N\n" +
	"\x06round2\x18\x05 \x01(\v24.getamis.alice.crypto.tss.ecdsa.cggmp.sign.Round2MsgH\x00R\x06round2\x12N\n" +
	"\x06round3\x18\x06 \x01(\v24.getamis.alice.crypto.tss.ecdsa.cggmp.sign.Round3MsgH\x00R\x06round3\x12N\n" +
	"\x06round4\x18\a \x01(\v24.getamis.alice.crypto.tss.ecdsa.cggmp.sign.Round4MsgH\x00R\x06round4\x12H\n" +
	"\x04err1\x18\b \x01(\v22.getamis.alice.crypto.tss.ecdsa.cggmp.sign.Err1MsgH\x00R\x04err1\x12H\n" +
	"\x04err2\x18\t \x01(\v22.getamis.alice.crypto.tss.ecdsa.cggmp.sign.Err2MsgH\x00R\x04err2B\x06\n" +
	"\x04body\"\xa5\x01\n" +
	"\tRound1Msg\x12 \n" +
	"\vkCiphertext\x18\x01 \x01(\fR\vkCiphertext\x12(\n" +
	"\x0fgammaCiphertext\x18\x02 \x01(\fR\x0fgammaCiphertext\x12L\n" +
	"\x03psi\x18\x03 \x01(\v2:.getamis.alice.crypto.zkproof.paillier.EncryptRangeMessageR\x03psi\"\xa4\x03\n" +
	"\tRound2Msg\x12\f\n" +
	"\x01D\x18\x01 \x01(\fR\x01D\x12\f\n" +
	"\x01F\x18\x02 \x01(\fR\x01F\x12\x12\n" +
	"\x04Dhat\x18\x03 \x01(\fR\x04Dhat\x12\x12\n" +
	"\x04Fhat\x18\x04 \x01(\fR\x04Fhat\x12X\n" +
	"\x03psi\x18\x05 \x01(\v2F.getamis.alice.crypto.zkproof.paillier.PaillierAffAndGroupRangeMessageR\x03psi\x12^\n" +
	"\x06psihat\x18\x06 \x01(\v2F.getamis.alice.crypto.zkproof.paillier.PaillierAffAndGroupRangeMessageR\x06psihat\x12M\n" +
	"\x06psipai\x18\a \x01(\v25.getamis.alice.crypto.zkproof.paillier.LogStarMessageR\x06psipai\x12J\n" +
	"\x05Gamma\x18\b \x01(\v24.getamis.alice.crypto.ecpointgrouplaw.EcPointMessageR\x05Gamma\"\xce\x01\n" +
	"\tRound3Msg\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\tR\x05delta\x12P\n" +
	"\bbigDelta\x18\x02 \x01(\v24.getamis.alice.crypto.ecpointgrouplaw.EcPointMessageR\bbigDelta\x12Y\n" +
	"\fpsidoublepai\x18\x03 \x01(\v25.getamis.alice.crypto.zkproof.paillier.LogStarMessageR\fpsidoublepai\"#\n" +
	"\tRound4Msg\x12\x16\n" +
	"\x06sigmai\x18\x01 \x01(\fR\x06sigmai\"\xcb\x02\n" +
	"\aErr1Msg\x12*\n" +
	"\x10kgammaCiphertext\x18\x01 \x01(\fR\x10kgammaCiphertext\x12M\n" +
	"\bmulProof\x18\x02 \x01(\v21.getamis.alice.crypto.zkproof.paillier.MulMessageR\bmulProof\x12S\n" +
	"\x05peers\x18\x03 \x03(\v2=.getamis.alice.crypto.tss.ecdsa.cggmp.sign.Err1Msg.PeersEntryR\x05peers\x1ap\n" +
	"\n" +
	"PeersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12L\n" +
	"\x05value\x18\x02 \x01(\v26.getamis.alice.crypto.tss.ecdsa.cggmp.sign.Err1PeerMsgR\x05value:\x028\x01\"\xa6\x01\n" +
	"\vErr1PeerMsg\x12M\n" +
	"\adecModQ\x18\x01 \x01(\v23.getamis.alice.crypto.zkproof.paillier.DecryMessageR\adecModQ\x12,\n" +
	"\x11productCiphertext\x18\x02 \x01(\fR\x11productCiphertext\x12\f\n" +
	"\x01d\x18\x03 \x01(\fR\x01d\x12\f\n" +
	"\x01f\x18\x04 \x01(\fR\x01f\"\x98\x02\n" +
	"\aErr2Msg\x124\n" +
	"\x15kMulBkShareCiphertext\x18\x01 \x01(\fR\x15kMulBkShareCiphertext\x12S\n" +
	"\x05peers\x18\x02 \x03(\v2=.getamis.alice.crypto.tss.ecdsa.cggmp.sign.Err2Msg.PeersEntryR\x05peers\x12\x10\n" +
	"\x03chi\x18\x03 \x01(\fR\x03chi\x1ap\n" +
	"\n" +
	"PeersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12L\n" +
	"\x05value\x18\x02 \x01(\v26.getamis.alice.crypto.tss.ecdsa.cggmp.sign.Err2PeerMsgR\x05value:\x028\x01\"\xd4\x02\n" +
	"\vErr2PeerMsg\x12Y\n" +
	"\fmulStarProof\x18\x01 \x01(\v25.getamis.alice.crypto.zkproof.paillier.MulStarMessageR\fmulStarProof\x12M\n" +
	"\adecModQ\x18\x02 \x01(\v23.getamis.alice.crypto.zkproof.paillier.DecryMessageR\adecModQ\x12,\n" +
	"\x11productCiphertext\x18\x03 \x01(\fR\x11productCiphertext\x12\f\n" +
	"\x01d\x18\x04 \x01(\fR\x01d\x12\f\n" +
	"\x01f\x18\x05 \x01(\fR\x01f\x12Q\n" +
	"\tdecModQKm\x18\x06 \x01(\v23.getamis.alice.crypto.zkproof.paillier.DecryMessageR\tdecModQKm*J\n" +
	"\x04Type\x12\n" +
	"\n" +
	"\x06Round1\x10\x00\x12\n" +
	"\n" +
	"\x06Round2\x10\x01\x12\n" +
	"\n" +
	"\x06Round3\x10\x02\x12\n" +
	"\n" +
	"\x06Round4\x10\x03\x12\b\n" +
	"\x04Err1\x10\x04\x12\b\n" +
	"\x04Err2\x10\x05B6Z4github.com/getamis/alice/crypto/tss/ecdsa/cggmp/signb\x06proto3"

var (
	file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_rawDescOnce sync.Once
	file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_rawDescData []byte
)

func file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_rawDescGZIP() []byte {
	file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_rawDescOnce.Do(func() {
		file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_rawDesc), len(file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_rawDesc)))
	})
	return file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_rawDescData
}

var file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_goTypes = []any{
	(Type)(0),                            // 0: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Type
	(*Message)(nil),                      // 1: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Message
	(*Round1Msg)(nil),                    // 2: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Round1Msg
	(*Round2Msg)(nil),                    // 3: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Round2Msg
	(*Round3Msg)(nil),                    // 4: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Round3Msg
	(*Round4Msg)(nil),                    // 5: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Round4Msg
	(*Err1Msg)(nil),                      // 6: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Err1Msg
	(*Err1PeerMsg)(nil),                  // 7: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Err1PeerMsg
	(*Err2Msg)(nil),                      // 8: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Err2Msg
	(*Err2PeerMsg)(nil),                  // 9: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Err2PeerMsg
	nil,                                  // 10: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Err1Msg.PeersEntry
	nil,                                  // 11: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Err2Msg.PeersEntry
	(*paillier.EncryptRangeMessage)(nil), // 12: getamis.alice.crypto.zkproof.paillier.EncryptRangeMessage
	(*paillier.PaillierAffAndGroupRangeMessage)(nil), // 13: getamis.alice.crypto.zkproof.paillier.PaillierAffAndGroupRangeMessage
	(*paillier.LogStarMessage)(nil),                  // 14: getamis.alice.crypto.zkproof.paillier.LogStarMessage
	(*ecpointgrouplaw.EcPointMessage)(nil),           // 15: getamis.alice.crypto.ecpointgrouplaw.EcPointMessage
	(*paillier.MulMessage)(nil),                      // 16: getamis.alice.crypto.zkproof.paillier.MulMessage
	(*paillier.DecryMessage)(nil),                    // 17: getamis.alice.crypto.zkproof.paillier.DecryMessage
	(*paillier.MulStarMessage)(nil),                  // 18: getamis.alice.crypto.zkproof.paillier.MulStarMessage
}
var file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_depIdxs = []int32{
	0,  // 0: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Message.type:type_name -> getamis.alice.crypto.tss.ecdsa.cggmp.sign.Type
	2,  // 1: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Message.round1:type_name -> getamis.alice.crypto.tss.ecdsa.cggmp.sign.Round1Msg
	3,  // 2: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Message.round2:type_name -> getamis.alice.crypto.tss.ecdsa.cggmp.sign.Round2Msg
	4,  // 3: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Message.round3:type_name -> getamis.alice.crypto.tss.ecdsa.cggmp.sign.Round3Msg
	5,  // 4: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Message.round4:type_name -> getamis.alice.crypto.tss.ecdsa.cggmp.sign.Round4Msg
	6,  // 5: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Message.err1:type_name -> getamis.alice.crypto.tss.ecdsa.cggmp.sign.Err1Msg
	8,  // 6: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Message.err2:type_name -> getamis.alice.crypto.tss.ecdsa.cggmp.sign.Err2Msg
	12, // 7: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Round1Msg.psi:type_name -> getamis.alice.crypto.zkproof.paillier.EncryptRangeMessage
	13, // 8: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Round2Msg.psi:type_name -> getamis.alice.crypto.zkproof.paillier.PaillierAffAndGroupRangeMessage
	13, // 9: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Round2Msg.psihat:type_name -> getamis.alice.crypto.zkproof.paillier.PaillierAffAndGroupRangeMessage
	14, // 10: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Round2Msg.psipai:type_name -> getamis.alice.crypto.zkproof.paillier.LogStarMessage
	15, // 11: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Round2Msg.Gamma:type_name -> getamis.alice.crypto.ecpointgrouplaw.EcPointMessage
	15, // 12: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Round3Msg.bigDelta:type_name -> getamis.alice.crypto.ecpointgrouplaw.EcPointMessage
	14, // 13: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Round3Msg.psidoublepai:type_name -> getamis.alice.crypto.zkproof.paillier.LogStarMessage
	16, // 14: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Err1Msg.mulProof:type_name -> getamis.alice.crypto.zkproof.paillier.MulMessage
	10, // 15: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Err1Msg.peers:type_name -> getamis.alice.crypto.tss.ecdsa.cggmp.sign.Err1Msg.PeersEntry
	17, // 16: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Err1PeerMsg.decModQ:type_name -> getamis.alice.crypto.zkproof.paillier.DecryMessage
	11, // 17: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Err2Msg.peers:type_name -> getamis.alice.crypto.tss.ecdsa.cggmp.sign.Err2Msg.PeersEntry
	18, // 18: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Err2PeerMsg.mulStarProof:type_name -> getamis.alice.crypto.zkproof.paillier.MulStarMessage
	17, // 19: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Err2PeerMsg.decModQ:type_name -> getamis.alice.crypto.zkproof.paillier.DecryMessage
	17, // 20: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Err2PeerMsg.decModQKm:type_name -> getamis.alice.crypto.zkproof.paillier.DecryMessage
	7,  // 21: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Err1Msg.PeersEntry.value:type_name -> getamis.alice.crypto.tss.ecdsa.cggmp.sign.Err1PeerMsg
	9,  // 22: getamis.alice.crypto.tss.ecdsa.cggmp.sign.Err2Msg.PeersEntry.value:type_name -> getamis.alice.crypto.tss.ecdsa.cggmp.sign.Err2PeerMsg
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_init() }
func file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_init() {
	if File_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto != nil {
		return
	}
	file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_Round1)(nil),
		(*Message_Round2)(nil),
		(*Message_Round3)(nil),
		(*Message_Round4)(nil),
		(*Message_Err1)(nil),
		(*Message_Err2)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_rawDesc), len(file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_goTypes,
		DependencyIndexes: file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_depIdxs,
		EnumInfos:         file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_enumTypes,
		MessageInfos:      file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_msgTypes,
	}.Build()
	File_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto = out.File
	file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_goTypes = nil
	file_github_com_getamis_alice_crypto_tss_ecdsa_cggmp_sign_message_proto_depIdxs = nil
}
